import numpy as np

BALL_COLOUR = {
    "lower": np.array([18, 100, 100]),
    "upper": np.array([40, 255, 255]),
}

MORPH_KERNEL_SIZE = (5, 5)
USE_MORPH_OPEN = False
USE_MORPH_CLOSE = True

MIN_AREA = 20
MAX_AREA = 500

MIN_CIRCULARITY = 0.5

MIN_ASPECT_RATIO = 0.7
MAX_ASPECT_RATIO = 1.3

MIN_RADIUS = 3
MAX_RADIUS = 30

# Drawing
POINT_RADIUS = 5
LINE_THICKNESS = 2
BALL_OUTLINE_THICKNESS = 2
CENTER_DOT_RADIUS = 3

POINT_COLOUR = (0, 0, 255)
LINE_COLOUR = (255, 0, 0)
BALL_COLOUR_DRAW = (0, 255, 0)
CENTER_COLOUR = (0, 0, 255)

SELECT_WINDOW_NAME = "Select Court"